# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
exclude: '^(.tox/|.*\.sh$)'
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      #- id: check-json
      - id: check-yaml
      #  exclude: '.pep8speaks.yml'

  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
      - id: black
        name: "Format code"
        language_version: python3

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        files: token_getter.py
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=148"]
        additional_dependencies: ["flake8-bugbear"]
        files: token_getter.py

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-ll"]
        files: token_getter.py

  #- repo: https://github.com/lovesegfault/beautysh
    #rev: v6.2.1
    #hooks:
      #- id: beautysh
